### ISSUE TITLE
Error loading any DOS executable in Ghidra 11

### ISSUE THREAD

**Issue by neuromancer** [Gravelbones/GhidraDosToolbox#4]
After recompiling for Ghidra 11.0.3 and loading any DOS executable, I'm getting this:

```
java.lang.ClassCastException: class ghidra.program.model.address.GenericAddress cannot be cast to class ghidra.program.model.address.SegmentedAddress (ghidra.program.model.address.GenericAddress and ghidra.program.model.address.SegmentedAddress are in unnamed module of loader ghidra.GhidraClassLoader @3aa9e816)
java.io.IOException: java.lang.ClassCastException: class ghidra.program.model.address.GenericAddress cannot be cast to class ghidra.program.model.address.SegmentedAddress (ghidra.program.model.address.GenericAddress and ghidra.program.model.address.SegmentedAddress are in unnamed module of loader ghidra.GhidraClassLoader @3aa9e816)
	at ghidradostoolbox.DosLoader.load(DosLoader.java:210)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.doLoad(AbstractLibrarySupportLoader.java:887)
	at ghidra.app.util.opinion.AbstractLibrarySupportLoader.loadProgram(AbstractLibrarySupportLoader.java:98)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:131)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:395)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:336)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.ClassCastException: class ghidra.program.model.address.GenericAddress cannot be cast to class ghidra.program.model.address.SegmentedAddress (ghidra.program.model.address.GenericAddress and ghidra.program.model.address.SegmentedAddress are in unnamed module of loader ghidra.GhidraClassLoader @3aa9e816)
	at ghidradostoolbox.DosLoader.processRegisters(DosLoader.java:422)
	at ghidradostoolbox.DosLoader.load(DosLoader.java:200)
	... 11 more

---------------------------------------------------
Build Date: 2024-Apr-11 1104 UTC
Ghidra Version: 11.0.3
Java Home: /usr/lib/jvm/java-23-openjdk
JVM Version: Arch Linux 23
OS: Linux 6.11.5-arch1-1 amd64
```

**Comment by Gravelbones** [comment]
Haven't been working with this for some time and haven't kept up with changes.
So yes, this is a change in version 11 that needs to be handled.
But for now I do not have time to look into all needed changes for version 11,
My code is built on the MzLoader class in Ghidra and will be a good place to look for changes.

**Comment by neuromancer** [comment]
Oh, it's ok. This issue only affects the experimental loader. The normal seems to work. I'm not sure about the difference between them. :thinking:

**Comment by neuromancer** [comment]
I have a very naive patch that fix the issue, but I'm not sure the results are good or not. Please take a look:

```diff
diff --git a/src/main/java/ghidradostoolbox/DosLoader.java b/src/main/java/ghidradostoolbox/DosLoader.java
index ce79bdf..90e09c5 100644
--- a/src/main/java/ghidradostoolbox/DosLoader.java
+++ b/src/main/java/ghidradostoolbox/DosLoader.java
@@ -418,23 +418,31 @@ public class DosLoader extends AbstractLibrarySupportLoader {
 			for (MemoryBlock block : program.getMemory().getBlocks()) {
 				// CS should point to segment for each loaded segment
 				// In case of a data segment that is pointless but do no harm
-				// Any jump/call into the segment should be a far one				
-				SegmentedAddress start = (SegmentedAddress) block.getStart();
-				if (!(start.getAddressSpace() instanceof SegmentedAddressSpace)) {
-					continue;
+				// Any jump/call into the segment should be a far one
+				Address startAddress = block.getStart();
+				if (startAddress instanceof SegmentedAddress) {
+					SegmentedAddress start = (SegmentedAddress) startAddress;
+
+					// Check if the address space is SegmentedAddressSpace
+					if (start.getAddressSpace() instanceof SegmentedAddressSpace) {
+						int csValue = start.getSegment();
+						Address end = block.getEnd();
+
+						// Set context values
+						context.setValue(cs, start, end, BigInteger.valueOf(csValue));
+						context.setValue(ds, start, end, BigInteger.valueOf(dsValue));
+					}
+				} else {
+					// Optionally log a warning for unexpected address types
+					System.err.println("Skipping block with non-segmented start address: " + startAddress.getClass().getName());
 				}
-
-				int csValue = start.getSegment();
-				Address end = block.getEnd();				
-				context.setValue(cs, start, end, BigInteger.valueOf(csValue));
-				context.setValue(ds, start, end, BigInteger.valueOf(dsValue));
 			}
 		}
 		catch (ContextChangeException e) {
 			// ignore since segment registers should never cause this error
 		}
 	}
-	
+
 	private void processHeaderStructures(Program program, SegmentedAddressSpace space, MzExecutable mz,
 			MessageLog log, TaskMonitor monitor, FileBytes fileBytes, List<Option> options) {
 		monitor.setMessage("Setting data and header information...");
```
